/* Défi du soir — contenu du jeu */
window.DDS_THEMES = {
  confiance:     { label: "Confiance en soi",       short: "Confiance",     emoji: "🦁", color: "#f59e0b" },
  discipline:    { label: "Discipline & habitudes", short: "Discipline",    emoji: "⏱️", color: "#22c55e" },
  leadership:    { label: "Leadership & management", short: "Leadership",   emoji: "🧭", color: "#3b82f6" },
  vente:         { label: "Communication & vente",  short: "Vente",         emoji: "🎯", color: "#ef4444" },
  finances:      { label: "Finances perso",         short: "Finances",      emoji: "💶", color: "#14b8a6" },
  bienetre:      { label: "Bien-être & sommeil",    short: "Bien-être",     emoji: "🌙", color: "#84cc16" },
  mental:        { label: "Gratitude & mental",     short: "Mental",        emoji: "🧘", color: "#a855f7" },
  apprentissage: { label: "Apprentissage",          short: "Apprentissage", emoji: "📚", color: "#ec4899" }
};

/* type : Journal | Réflexion | Action | Exercice  —  min : durée estimée */
window.DDS_CHALLENGES = [
  // ── Confiance en soi ──
  { id: "c1", theme: "confiance", type: "Journal", min: 15, title: "Le dossier des victoires",
    prompt: "Listez 10 réussites de votre vie, petites ou grandes : un diplôme, un objectif atteint, une vente difficile, une personne aidée… Pour chacune, notez la qualité qu'elle prouve chez vous.",
    ph: "1. … → qualité : …" },
  { id: "c2", theme: "confiance", type: "Réflexion", min: 10, title: "Votre voix intérieure",
    prompt: "Repérez une phrase négative que vous vous êtes dite aujourd'hui. Écrivez-la, puis réécrivez-la comme le ferait un coach bienveillant mais exigeant.",
    ph: "Ce que je me suis dit : … / Ce que mon coach me dirait : …" },
  { id: "c3", theme: "confiance", type: "Action", min: 10, title: "Un pas hors de la zone de confort",
    prompt: "Choisissez une micro-action qui vous fait un peu peur, à faire demain : appeler quelqu'un, prendre la parole en premier, demander un retour honnête. Écrivez-la avec l'heure précise où vous la ferez.",
    ph: "Demain à …h, je vais …" },
  { id: "c4", theme: "confiance", type: "Réflexion", min: 10, title: "Votre meilleure version",
    prompt: "Repensez à un moment où vous vous êtes senti inarrêtable. Décrivez-le en détail : où vous étiez, ce que vous pensiez, ce que vous disiez. Trouvez une phrase-clé qui vous ramène à cet état, et notez dans quelle situation de demain vous l'utiliserez.",
    ph: "Le moment : … / Ma phrase-clé : « … » / Demain, je l'utiliserai quand…" },
  { id: "c5", theme: "confiance", type: "Journal", min: 15, title: "Lettre à vous-même à 17 ans",
    prompt: "Écrivez quelques lignes à la personne que vous étiez à 17 ans : ce dont elle serait fière aujourd'hui, et ce que vous lui diriez de ne plus craindre.",
    ph: "Salut, toi à 17 ans…" },
  { id: "c6", theme: "confiance", type: "Réflexion", min: 10, title: "Vos 3 forces",
    prompt: "Quelles sont vos 3 plus grandes forces ? Pour chacune, donnez un exemple concret des 30 derniers jours où vous l'avez utilisée.",
    ph: "Force 1 : … Exemple : …" },
  { id: "c7", theme: "confiance", type: "Réflexion", min: 15, title: "Le regard des autres",
    prompt: "Pensez à une décision que vous repoussez par peur du jugement. Écrivez le pire scénario réaliste, le meilleur, puis le plus probable. Que décidez-vous ?",
    ph: "Pire : … / Meilleur : … / Probable : … / Ma décision : …" },
  { id: "c8", theme: "confiance", type: "Journal", min: 10, title: "Le compliment accepté",
    prompt: "Quel est le dernier compliment que vous avez reçu ? L'avez-vous vraiment accepté ? Écrivez pourquoi il était mérité.",
    ph: "On m'a dit… C'était mérité parce que…" },
  { id: "c9", theme: "confiance", type: "Réflexion", min: 15, title: "Votre identité future",
    prompt: "Décrivez en 5 lignes la personne que vous serez dans 3 ans : travail, état d'esprit, argent, relations. Puis écrivez une seule chose que cette personne ferait demain à votre place.",
    ph: "Dans 3 ans, je suis… Demain, il/elle ferait…" },
  { id: "c10", theme: "confiance", type: "Journal", min: 15, title: "Ce que l'échec m'a appris",
    prompt: "Racontez un échec passé et listez 3 choses qu'il vous a apprises. Que feriez-vous différemment aujourd'hui ?",
    ph: "L'échec : … Leçons : 1… 2… 3…" },

  // ── Discipline & habitudes ──
  { id: "d1", theme: "discipline", type: "Réflexion", min: 10, title: "L'audit de votre journée",
    prompt: "Reprenez votre journée heure par heure. Où avez-vous perdu du temps ? Quel moment a été le plus productif ? Fixez une règle simple pour demain.",
    ph: "Temps perdu : … / Meilleur moment : … / Règle pour demain : …" },
  { id: "d2", theme: "discipline", type: "Action", min: 10, title: "Les 3 priorités de demain",
    prompt: "Écrivez les 3 tâches qui, si elles sont faites demain, rendront la journée réussie. Classez-les par ordre d'importance et estimez la durée de chacune.",
    ph: "1. … (… min)\n2. …\n3. …" },
  { id: "d3", theme: "discipline", type: "Action", min: 10, title: "Une habitude de 2 minutes",
    prompt: "Choisissez une habitude à installer (lecture, journal, méditation…). Réduisez-la à une version de 2 minutes et accrochez-la à une habitude existante : « Après ___, je ferai ___. »",
    ph: "Après …, je ferai …" },
  { id: "d4", theme: "discipline", type: "Exercice", min: 10, title: "Le téléphone, voleur de temps",
    prompt: "Ouvrez Réglages › Temps d'écran sur votre iPhone. Combien d'heures aujourd'hui ? Quelle appli arrive en tête ? Fixez une limite concrète pour demain (et activez-la).",
    ph: "Aujourd'hui : …h / Appli n°1 : … / Limite demain : …" },
  { id: "d5", theme: "discipline", type: "Exercice", min: 15, title: "Votre routine du soir",
    prompt: "Concevez votre routine idéale pour les 30 minutes avant de dormir, sans écran si possible. Écrivez-la étape par étape et testez-la dès ce soir.",
    ph: "22h30 : … / 22h40 : … / 23h00 : dodo" },
  { id: "d6", theme: "discipline", type: "Action", min: 15, title: "Votre routine du matin",
    prompt: "Concevez une routine matinale de 15 minutes qui vous met en mode « gagnant » avant le travail. Préparez dès ce soir ce qu'il faut : tenue, eau, réveil.",
    ph: "Ma routine : 1… 2… 3… / Préparé ce soir : …" },
  { id: "d7", theme: "discipline", type: "Action", min: 10, title: "Supprimer une friction",
    prompt: "Quelle mauvaise habitude voulez-vous réduire ? Trouvez une façon de la rendre plus difficile (ranger, déconnecter, supprimer un raccourci) et faites-le maintenant.",
    ph: "Habitude : … / Ce que j'ai changé : …" },
  { id: "d8", theme: "discipline", type: "Action", min: 10, title: "La tâche repoussée",
    prompt: "Pensez à une tâche que vous repoussez depuis des jours. Pourquoi la repoussez-vous ? Écrivez sa toute première étape (moins de 5 minutes) et l'heure à laquelle vous la ferez demain.",
    ph: "Tâche : … / Pourquoi : … / 1re étape demain à …h : …" },
  { id: "d9", theme: "discipline", type: "Réflexion", min: 10, title: "Les promesses à soi-même",
    prompt: "Avez-vous tenu toutes les promesses faites à vous-même cette semaine ? Écrivez-en une non tenue et ce qui vous a bloqué. Comment rendre la prochaine plus simple à tenir ?",
    ph: "Promesse : … / Blocage : … / Version plus simple : …" },
  { id: "d10", theme: "discipline", type: "Exercice", min: 10, title: "Préparer demain en 10 minutes",
    prompt: "Préparez concrètement demain : tenue, sac, repas, agenda vérifié. Notez ce que vous avez préparé et le temps ou le stress que cela vous fera gagner.",
    ph: "Préparé : … / Gain : …" },

  // ── Leadership & management ──
  { id: "l1", theme: "leadership", type: "Action", min: 10, title: "Le tête-à-tête qui compte",
    prompt: "Choisissez un membre de votre équipe que vous avez peu vu cette semaine. Écrivez 3 questions ouvertes à lui poser demain sur ses objectifs et ses difficultés.",
    ph: "Pour … : 1. … 2. … 3. …" },
  { id: "l2", theme: "leadership", type: "Action", min: 10, title: "Un merci précis",
    prompt: "Qui dans votre équipe mérite un vrai merci ? Rédigez le message exact : le fait concret + son impact. Envoyez-le demain.",
    ph: "« …, merci pour … ça a permis … »" },
  { id: "l3", theme: "leadership", type: "Réflexion", min: 15, title: "Pourquoi ils restent",
    prompt: "Pensez à la personne restée le plus longtemps dans votre équipe. Qu'est-ce qui l'a fait rester ? Comment reproduire cela avec chaque nouvelle recrue ?",
    ph: "Ce qui l'a fait rester : … / À reproduire : …" },
  { id: "l4", theme: "leadership", type: "Réflexion", min: 10, title: "Le leader que vous voulez être",
    prompt: "Décrivez le meilleur manager que vous ayez eu (ou imaginé). Quelles sont ses 3 qualités ? Laquelle travaillez-vous dès demain, et comment ?",
    ph: "Qualités : … / Demain je travaille : …" },
  { id: "l5", theme: "leadership", type: "Exercice", min: 15, title: "Un feedback en SCI",
    prompt: "Préparez un retour pour un membre de l'équipe avec la méthode SCI : Situation (quand, où), Comportement (ce que vous avez observé), Impact (l'effet). Écrivez-le mot pour mot.",
    ph: "Situation : … / Comportement : … / Impact : …" },
  { id: "l6", theme: "leadership", type: "Réflexion", min: 10, title: "Déléguer pour faire grandir",
    prompt: "Quelle tâche faites-vous vous-même alors qu'un membre de l'équipe pourrait la faire, et progresser grâce à elle ? À qui la confier, et comment la lui expliquer ?",
    ph: "Tâche : … / À : … / Comment : …" },
  { id: "l7", theme: "leadership", type: "Réflexion", min: 10, title: "La météo de l'équipe",
    prompt: "Notez de 1 à 10 le moral de votre équipe cette semaine. Qu'est-ce qui l'a fait monter ou descendre ? Trouvez une action simple pour le relever demain.",
    ph: "Note : …/10 / Pourquoi : … / Action : …" },
  { id: "l8", theme: "leadership", type: "Réflexion", min: 15, title: "Dans la peau d'une recrue",
    prompt: "Imaginez que vous êtes une nouvelle recrue payée à la commission. Qu'auriez-vous besoin d'entendre et de vivre dès le premier jour pour avoir envie de revenir le lendemain ?",
    ph: "J'aurais besoin de…" },
  { id: "l9", theme: "leadership", type: "Réflexion", min: 10, title: "Montrer l'exemple",
    prompt: "Quel comportement attendez-vous de l'équipe que vous ne montrez pas toujours vous-même ? Comment allez-vous l'incarner demain ?",
    ph: "Comportement : … / Demain, je…" },
  { id: "l10", theme: "leadership", type: "Exercice", min: 15, title: "Le brief qui motive",
    prompt: "Rédigez un brief de 60 secondes pour lancer la journée de demain : un objectif clair, une raison d'y croire, une énergie. Lisez-le à voix haute deux fois.",
    ph: "« Aujourd'hui, l'objectif c'est… »" },

  // ── Communication & vente ──
  { id: "v1", theme: "vente", type: "Exercice", min: 15, title: "Votre accroche en 30 secondes",
    prompt: "Réécrivez votre accroche (porte-à-porte ou téléphone) pour qu'elle tienne en moins de 30 secondes. Enregistrez-vous avec le dictaphone, réécoutez et notez ce que vous changeriez.",
    ph: "Mon accroche : … / À améliorer : …" },
  { id: "v2", theme: "vente", type: "Exercice", min: 15, title: "Les 3 objections",
    prompt: "Listez les 3 objections que vous entendez le plus. Pour chacune, écrivez une réponse qui commence par une question plutôt que par un argument.",
    ph: "« C'est trop cher » → « … ? »" },
  { id: "v3", theme: "vente", type: "Action", min: 10, title: "L'écoute active",
    prompt: "Pendant une conversation ce soir, reformulez ce que dit l'autre avant de répondre (« Si je comprends bien… »). Notez comment la conversation a changé.",
    ph: "Avec qui : … / Ce que j'ai remarqué : …" },
  { id: "v4", theme: "vente", type: "Réflexion", min: 10, title: "Autopsie d'une vente",
    prompt: "Repensez à votre dernière vente réussie, ou à celle d'un membre de l'équipe. Quel a été le moment décisif ? Comment le reproduire volontairement ?",
    ph: "Moment décisif : … / Pour le reproduire : …" },
  { id: "v5", theme: "vente", type: "Réflexion", min: 10, title: "Autopsie d'un non",
    prompt: "Repensez à un refus récent. À quel moment le client a-t-il décroché ? Quelle question auriez-vous pu poser à ce moment-là ?",
    ph: "Il a décroché quand… / J'aurais pu demander…" },
  { id: "v6", theme: "vente", type: "Exercice", min: 15, title: "Les questions de découverte",
    prompt: "Écrivez 5 questions de découverte qui font parler le client de ce qui compte pour lui (sa famille, sa tranquillité, son quotidien), sans jamais parler du produit.",
    ph: "1. … ?\n2. … ?" },
  { id: "v7", theme: "vente", type: "Journal", min: 15, title: "Raconter une histoire",
    prompt: "Écrivez une courte histoire client, vraie et anonymisée, qui illustre la valeur de ce que vous vendez. Six phrases maximum, avec un avant et un après.",
    ph: "Il y a quelques mois, un client…" },
  { id: "v8", theme: "vente", type: "Exercice", min: 10, title: "Votre langage non verbal",
    prompt: "Faites votre pitch devant un miroir ou filmez-vous 1 minute. Listez 3 signaux non verbaux à améliorer : sourire, regard, mains, débit.",
    ph: "1. … 2. … 3. …" },
  { id: "v9", theme: "vente", type: "Réflexion", min: 10, title: "Dire non avec classe",
    prompt: "À quelle demande avez-vous dit oui récemment alors que vous vouliez dire non ? Écrivez comment vous la refuseriez, poliment et fermement.",
    ph: "La demande : … / Ma réponse : « … »" },
  { id: "v10", theme: "vente", type: "Exercice", min: 15, title: "La conversation évitée",
    prompt: "Y a-t-il une conversation que vous évitez (collègue, proche, manager) ? Écrivez les 3 premières phrases pour l'ouvrir calmement, puis décidez quand vous l'aurez.",
    ph: "« J'aimerais qu'on parle de… »" },

  // ── Finances perso ──
  { id: "f1", theme: "finances", type: "Exercice", min: 20, title: "Où va votre argent ?",
    prompt: "Ouvrez votre appli bancaire et classez vos dépenses des 30 derniers jours en 3 catégories : essentiel, plaisir, inutile. Quel montant aurait pu être économisé ?",
    ph: "Essentiel : … € / Plaisir : … € / Inutile : … €" },
  { id: "f2", theme: "finances", type: "Exercice", min: 15, title: "Votre matelas de sécurité",
    prompt: "Calculez vos dépenses mensuelles fixes. Combien vous faudrait-il de côté pour tenir 3 mois sans revenu ? Où en êtes-vous aujourd'hui ?",
    ph: "Dépenses fixes : … €/mois → objectif : … € / Aujourd'hui : … €" },
  { id: "f3", theme: "finances", type: "Action", min: 10, title: "Payez-vous en premier",
    prompt: "Décidez d'un montant, même 20 €, à virer automatiquement sur une épargne le jour de la paie. Notez le montant et la date à laquelle vous programmez le virement.",
    ph: "Montant : … € / Programmé le : …" },
  { id: "f4", theme: "finances", type: "Exercice", min: 10, title: "L'abonnement de trop",
    prompt: "Listez tous vos abonnements : streaming, applis, presse, téléphone… Lequel pouvez-vous résilier ou partager ? Calculez l'économie sur un an.",
    ph: "Abonnements : … / À couper : … → … €/an" },
  { id: "f5", theme: "finances", type: "Exercice", min: 15, title: "Un concept d'investissement",
    prompt: "Renseignez-vous 10 minutes sur un concept : ETF, PEA, diversification, frais de gestion… Puis expliquez-le avec vos mots, comme à un ami.",
    ph: "Le concept : … En gros, c'est…" },
  { id: "f6", theme: "finances", type: "Réflexion", min: 10, title: "La magie des intérêts composés",
    prompt: "100 € placés chaque mois pendant 20 ans à 6 % par an deviennent environ 46 000 €, dont seulement 24 000 € versés. Qu'est-ce que ça change dans votre façon de voir l'épargne ? Quel montant mensuel visez-vous ?",
    ph: "Ce que ça m'inspire : … / Mon montant : … €/mois" },
  { id: "f7", theme: "finances", type: "Réflexion", min: 15, title: "Idée de revenu complémentaire",
    prompt: "Listez 5 compétences ou atouts que vous avez (vente, management, réseau…). Pour 2 d'entre eux, imaginez une façon concrète d'en tirer un revenu complémentaire, et la première étape.",
    ph: "Atouts : … / Idée 1 : … / Idée 2 : …" },
  { id: "f8", theme: "finances", type: "Réflexion", min: 10, title: "L'achat impulsif",
    prompt: "Quel est votre dernier achat regretté ? Qu'est-ce qui l'a déclenché ? Créez votre règle anti-impulsion (ex : attendre 48 h pour tout achat au-delà de 50 €).",
    ph: "Achat : … / Déclencheur : … / Ma règle : …" },
  { id: "f9", theme: "finances", type: "Action", min: 15, title: "Objectif financier à 12 mois",
    prompt: "Fixez un objectif chiffré pour dans 12 mois : épargne, dette remboursée, investissement. Découpez-le en montant par mois et par semaine.",
    ph: "Objectif : … € → … €/mois → … €/semaine" },
  { id: "f10", theme: "finances", type: "Exercice", min: 15, title: "Faire le point sur ce que l'on doit",
    prompt: "Listez tout ce que vous devez encore (crédits, paiements en plusieurs fois, amendes…) avec le montant restant. Quel est le plan pour solder le plus urgent ?",
    ph: "… : … € restants / Plan : …" },

  // ── Bien-être & sommeil ──
  { id: "b1", theme: "bienetre", type: "Réflexion", min: 10, title: "Bilan sommeil",
    prompt: "À quelle heure vous êtes-vous couché et levé ces 3 derniers jours ? Combien d'heures cela fait-il ? Fixez une heure de coucher pour ce soir et tenez-la.",
    ph: "J1 : …h → …h / J2 : … / J3 : … / Ce soir : au lit à …h" },
  { id: "b2", theme: "bienetre", type: "Action", min: 10, title: "Écrans éteints",
    prompt: "Ce soir, plus d'écran 45 minutes avant de dormir. Écrivez ce que vous allez faire à la place (lecture, discussion, musique douce, préparer demain…). Demain, notez la qualité de votre sommeil.",
    ph: "À la place, je vais…" },
  { id: "b3", theme: "bienetre", type: "Action", min: 10, title: "La chambre refuge",
    prompt: "Votre chambre aide-t-elle à bien dormir ? Passez-la en revue : lumière, bruit, téléphone près du lit, désordre. Choisissez un seul changement à faire dès ce soir (par exemple, téléphone en charge hors de la chambre).",
    ph: "Ce qui gêne : … / Mon changement dès ce soir : …" },
  { id: "b4", theme: "bienetre", type: "Réflexion", min: 10, title: "Le baromètre du stress",
    prompt: "Notez votre niveau de stress de la journée, de 1 à 10. Quelles en ont été les 3 sources principales ? Pour chacune, trouvez une petite chose qui l'allégerait demain.",
    ph: "Stress : …/10 / Sources : 1… 2… 3… / Pour alléger : …" },
  { id: "b5", theme: "bienetre", type: "Exercice", min: 10, title: "Reporter ses soucis",
    prompt: "Écrivez tous les soucis qui pourraient vous empêcher de dormir. Pour chacun, notez quand vous vous en occuperez (jour et heure). Une fois sur le papier, ils peuvent attendre demain.",
    ph: "Souci : … → je m'en occupe le … à …h" },
  { id: "b6", theme: "bienetre", type: "Réflexion", min: 10, title: "Ce qui vous recharge",
    prompt: "Faites deux listes : ce qui vous a vidé d'énergie cette semaine (personnes, tâches, habitudes) et ce qui vous a rechargé. Comment ajouter une recharge et retirer une fuite la semaine prochaine ?",
    ph: "Me vide : … / Me recharge : … / Semaine prochaine : …" },
  { id: "b7", theme: "bienetre", type: "Journal", min: 10, title: "Les petits plaisirs",
    prompt: "Listez 10 petits plaisirs simples, sans écran, qui vous font du bien : un bon café, une musique, un appel à un ami… Choisissez-en un à vous offrir demain, et notez quand.",
    ph: "1. … 2. … / Demain, je m'offre : … à …h" },
  { id: "b8", theme: "bienetre", type: "Exercice", min: 10, title: "Notifications sous contrôle",
    prompt: "Ouvrez Réglages › Notifications sur votre iPhone. Coupez celles qui ne sont pas indispensables et programmez le mode Concentration « Sommeil ». Notez combien d'applis vous avez fait taire.",
    ph: "Applis coupées : … / Mode Sommeil : de …h à …h" },
  { id: "b9", theme: "bienetre", type: "Réflexion", min: 10, title: "La frontière boulot-maison",
    prompt: "À quelle heure arrêtez-vous vraiment de penser au travail et de regarder vos messages pro ? Fixez une heure limite et un petit rituel qui marque la fin de la journée de travail.",
    ph: "Heure limite : …h / Mon rituel de fin de journée : …" },
  { id: "b10", theme: "bienetre", type: "Exercice", min: 10, title: "Votre refuge mental",
    prompt: "Fermez les yeux et imaginez un lieu où vous vous sentez parfaitement calme, réel ou inventé. Décrivez-le en détail : ce que vous voyez, entendez, ressentez. Vous pourrez y revenir en pensée dans les moments de stress.",
    ph: "Mon refuge : … / J'y vois… / J'y entends…" },

  // ── Gratitude & mental ──
  { id: "g1", theme: "mental", type: "Journal", min: 10, title: "Trois bonnes choses",
    prompt: "Écrivez 3 choses qui se sont bien passées aujourd'hui et, pour chacune, pourquoi elle s'est produite.",
    ph: "1. … parce que …" },
  { id: "g2", theme: "mental", type: "Journal", min: 15, title: "Merci à quelqu'un",
    prompt: "Pensez à une personne qui a compté dans votre parcours. Écrivez-lui un message de remerciement sincère. Vous choisirez ensuite de l'envoyer ou non.",
    ph: "Cher/Chère …," },
  { id: "g3", theme: "mental", type: "Exercice", min: 10, title: "Ce qui dépend de vous",
    prompt: "Listez ce qui vous préoccupe en ce moment. Séparez ce que vous contrôlez de ce que vous ne contrôlez pas. Choisissez une action sur la première liste.",
    ph: "Je contrôle : … / Je ne contrôle pas : … / Action : …" },
  { id: "g4", theme: "mental", type: "Exercice", min: 10, title: "Méditation 5 minutes",
    prompt: "Asseyez-vous 5 minutes, yeux fermés. Comptez vos respirations jusqu'à 10, puis recommencez. Notez combien de fois votre esprit s'est échappé, et vers quoi.",
    ph: "Échappées : … fois, vers : …" },
  { id: "g5", theme: "mental", type: "Journal", min: 10, title: "Vider la tête",
    prompt: "Écrivez sans vous arrêter pendant 5 minutes tout ce qui vous passe par la tête. Terminez en notant une seule chose à traiter demain.",
    ph: "Tout ce qui me passe par la tête…" },
  { id: "g6", theme: "mental", type: "Journal", min: 15, title: "La journée parfaite",
    prompt: "Décrivez une journée ordinaire parfaite pour vous dans 5 ans, du réveil au coucher. Qu'est-ce qui vous surprend dans ce que vous avez écrit ?",
    ph: "Je me réveille à …" },
  { id: "g7", theme: "mental", type: "Réflexion", min: 10, title: "Recadrer une contrariété",
    prompt: "Quelle contrariété avez-vous vécue aujourd'hui ? Trouvez 2 façons positives ou utiles de la voir.",
    ph: "Contrariété : … / Angle 1 : … / Angle 2 : …" },
  { id: "g8", theme: "mental", type: "Réflexion", min: 10, title: "Votre entourage",
    prompt: "Avec quelles 5 personnes passez-vous le plus de temps ? Lesquelles vous tirent vers le haut ? Comment passer plus de temps avec elles ?",
    ph: "1. … ↑ / 2. … / Plus de temps avec : …" },
  { id: "g9", theme: "mental", type: "Journal", min: 10, title: "La fierté du jour",
    prompt: "De quoi êtes-vous fier aujourd'hui, même si c'est petit ? Pourquoi est-ce important pour vous ?",
    ph: "Je suis fier de…" },
  { id: "g10", theme: "mental", type: "Réflexion", min: 15, title: "Vos valeurs",
    prompt: "Choisissez vos 3 valeurs les plus importantes (loyauté, liberté, famille, excellence, respect…). Votre semaine a-t-elle été alignée avec elles ? Où l'a-t-elle moins été ?",
    ph: "Mes valeurs : … / Aligné : … / Moins aligné : …" },

  // ── Apprentissage ──
  { id: "a1", theme: "apprentissage", type: "Réflexion", min: 10, title: "La leçon du jour",
    prompt: "Qu'avez-vous appris aujourd'hui, au travail, dans une conversation ou une vidéo ? Expliquez-le en 3 phrases, comme si vous l'enseigniez à quelqu'un.",
    ph: "Aujourd'hui j'ai appris que…" },
  { id: "a2", theme: "apprentissage", type: "Exercice", min: 20, title: "10 pages",
    prompt: "Lisez 10 pages d'un livre (développement perso, vente, biographie…). Notez l'idée principale et comment vous allez l'appliquer.",
    ph: "Livre : … / Idée : … / Application : …" },
  { id: "a3", theme: "apprentissage", type: "Action", min: 10, title: "Votre liste de lecture",
    prompt: "Établissez une liste de 5 livres ou podcasts à découvrir dans les 3 prochains mois (idées : « Influence » de Cialdini, « Atomic Habits » de James Clear, « L'homme le plus riche de Babylone »). Lequel commencez-vous cette semaine ?",
    ph: "1. … 2. … 3. … / Je commence : …" },
  { id: "a4", theme: "apprentissage", type: "Exercice", min: 15, title: "Apprendre d'un modèle",
    prompt: "Choisissez une personne que vous admirez (entrepreneur, leader, artiste). Renseignez-vous 10 minutes sur une habitude qui a fait son succès. Comment l'adapter à votre vie ?",
    ph: "Modèle : … / Son habitude : … / Ma version : …" },
  { id: "a5", theme: "apprentissage", type: "Réflexion", min: 10, title: "La compétence à 12 mois",
    prompt: "Quelle compétence, si vous la maîtrisiez dans un an, changerait le plus votre carrière ? Quelle première ressource allez-vous utiliser cette semaine ?",
    ph: "Compétence : … / Ressource : …" },
  { id: "a6", theme: "apprentissage", type: "Exercice", min: 15, title: "La technique Feynman",
    prompt: "Choisissez un sujet que vous pensez bien connaître. Expliquez-le par écrit comme à un enfant de 12 ans. Repérez les endroits où vous bloquez : ce sont vos trous à combler.",
    ph: "Sujet : … / Explication simple : …" },
  { id: "a7", theme: "apprentissage", type: "Exercice", min: 15, title: "15 minutes utiles",
    prompt: "Remplacez 15 minutes de scroll par une vidéo ou un podcast éducatif (vente, finances, management). Notez 3 idées retenues.",
    ph: "Vidéo : … / Idées : 1… 2… 3…" },
  { id: "a8", theme: "apprentissage", type: "Action", min: 10, title: "Demander conseil",
    prompt: "À qui pourriez-vous demander conseil cette semaine : un manager plus expérimenté, un entrepreneur, un ancien ? Écrivez la question précise que vous lui poserez.",
    ph: "À : … / Ma question : « … »" },
  { id: "a9", theme: "apprentissage", type: "Réflexion", min: 10, title: "La revue d'erreurs",
    prompt: "Quelle erreur avez-vous faite cette semaine ? Qu'est-ce qu'elle vous enseigne ? Écrivez la règle que vous en tirez pour la suite.",
    ph: "Erreur : … / Leçon : … / Ma règle : …" },
  { id: "a10", theme: "apprentissage", type: "Exercice", min: 15, title: "5 expressions en anglais",
    prompt: "Apprenez 5 mots ou expressions en anglais utiles pour le business (ex : « follow-up », « to close a deal », « pipeline »). Écrivez une phrase avec chacun.",
    ph: "1. … : « … »" }
];

window.DDS_LEVELS = [
  { xp: 0,     title: "Recrue" },
  { xp: 100,   title: "Apprenti" },
  { xp: 250,   title: "Challenger" },
  { xp: 450,   title: "Combattant" },
  { xp: 700,   title: "Bâtisseur" },
  { xp: 1000,  title: "Stratège" },
  { xp: 1400,  title: "Capitaine" },
  { xp: 1900,  title: "Leader" },
  { xp: 2500,  title: "Mentor" },
  { xp: 3200,  title: "Maître de soi" },
  { xp: 4000,  title: "Visionnaire" },
  { xp: 5000,  title: "Inarrêtable" },
  { xp: 6200,  title: "Élite" },
  { xp: 7600,  title: "Champion" },
  { xp: 9200,  title: "Icône" },
  { xp: 11000, title: "Légende" }
];

window.DDS_QUOTES = [
  "La discipline, c'est choisir entre ce que l'on veut maintenant et ce que l'on veut le plus.",
  "On ne monte pas en niveau par hasard : on y monte un soir après l'autre.",
  "Les petites actions répétées battent les grandes résolutions oubliées.",
  "Le vrai travail sur soi, c'est celui que l'on fait quand personne ne regarde.",
  "Vous n'avez pas à être parfait, seulement présent ce soir.",
  "Ce que vous faites chaque jour compte plus que ce que vous faites de temps en temps.",
  "Le meilleur moment pour commencer, c'était hier. Le deuxième meilleur, c'est ce soir.",
  "Prendre soin de son esprit, c'est préparer toutes ses victoires de demain.",
  "On devient ce que l'on répète.",
  "Chaque soir, 1 % de mieux. En un an, vous serez méconnaissable.",
  "La confiance n'est pas un point de départ, c'est un résultat.",
  "Un leader ne crée pas des suiveurs, il crée d'autres leaders."
];
